---
lab_specifics:
  lab_id: 3603
  vlans:
    openstack_vxlan_tenant:
      vlan_id: 16
      tagged_traffic_needed: true
      network: 172.16.0.0
      netmask: 255.255.0.0

    openstack_provider_vlan:
      vlan_id: 1
      tagged_traffic_needed: false
      network: 10.75.138.0
      netmask: 255.255.254.0
      broadcast: 10.75.139.255
      host_min: 10.75.138.41
      host_max: 10.75.138.49
      gateway: 10.75.138.1
      ntp_server: 10.250.32.10
      name_server: 10.209.76.197
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem1

    ext_management_vlan:
      vlan_id: 1
      tagged_traffic_needed: false
      network: 10.75.138.0
      netmask: 255.255.254.0
      broadcast: 10.75.139.255
      host_min: 10.75.138.38
      host_max: 10.75.138.49
      gateway: 10.75.138.1
      ntp_server: 10.250.32.10
      name_server: 10.209.76.197
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      blades:
        # chassis onap2
        c00b00: 10.75.138.39
        c00b01: 10.75.138.40
      utility_servers:
        x5-200: 10.75.138.38

    int_management_vlan:
      vlan_id: 1 
      tagged_traffic_needed: false
      network: 172.31.0.0
      netmask: 255.255.0.0
      broadcast: 172.31.255.255
      host_min: 172.31.2.1
      host_max: 172.31.2.254
      gateway: 172.31.254.254
      ntp_server: 10.250.32.10
      name_server: 10.209.76.197
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      utility_servers:
        x5-200: 172.31.254.254
      blades:
        c00b00: 172.31.2.110
        c00b01: 172.31.2.111

    ilom_vlan:
      vlan_id: 1
      tagged_traffic_needed: false
      network: 10.75.129.0
      netmask: 255.255.255.0
      broadcast: 10.75.129.255
      cmms:
        c00: 172.31.2.253
      nems:
        c00n00: 172.31.2.251
        c00n01: 172.31.2.252
      blades:
        c00b00: 10.75.129.45
        c00b01: 10.75.129.47
      utility_servers:
        x5-200: 10.75.129.46

  dhcp_subnets:
    info:
      base: 172.31.0.0
      netmask: 255.255.0.0
      routers: 172.31.254.254

