---
lab_specifics:
  lab_id: bigcloud
  vlans:
    openstack_vxlan_tenant:
      vlan_id: 11
      tagged_traffic_needed: true
      network: 172.16.0.0
      netmask: 255.255.0.0

    openstack_provider_vlan:
      tagged_traffic_needed: false
      vlan_id: 
      network: 10.75.183.0
      netmask: 255.255.255.128
      broadcast: 10.75.183.127 
      host_min: 10.75.183.65
      host_max: 10.75.183.126
      #openstack_reserved_first_address: 10.240.121.90
      #openstack_reserved_last_address: 10.240.121.100
      gateway: 10.75.183.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.10
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      utility_servers:
        bigcloud0100: 10.75.183.49
    ext_management_vlan:
      tagged_traffic_needed: false
      vlan_id: 20
      network: 10.75.183.0
      netmask: 255.255.255.128
      broadcast: 10.75.183.127
      host_min: 10.75.183.4
      host_max: 10.75.183.64
      gateway: 10.75.183.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.10
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      utility_servers:
        bigcloud0100: 10.75.183.49
      zfs:
        zfs00:
          head00: 10.250.54.111
          head01: 10.250.54.112
      blades:
        # Frame 100.09: X6-2 computes
        c00b00: 10.75.183.2
        c00b01: 10.75.183.3
        c00b02: 10.75.183.4
        c00b03: 10.75.183.5
        c00b04: 10.75.183.6
        c00b05: 10.75.183.7
        c00b06: 10.75.183.8
        c00b07: 10.75.183.9
        c00b08: 10.75.183.10
        c00b09: 10.75.183.11
        c00b10: 10.75.183.12
        c00b11: 10.75.183.13
        c00b12: 10.75.183.14
        c00b13: 10.75.183.15
        c00b14: 10.75.183.16
        c00b15: 10.75.183.17
        c00b16: 10.75.183.18
        c00b17: 10.75.183.19
        c00b18: 10.75.183.20
        c00b19: 10.75.183.21
        c00b20: 10.75.183.22
        c00b21: 10.75.183.23
        c00b22: 10.75.183.24
        c00b23: 10.75.183.25
        c00b24: 10.75.183.26
        c00b25: 10.75.183.27
        c00b26: 10.75.183.28
        c00b27: 10.75.183.29
        c00b28: 10.75.183.30
        c00b29: 10.75.183.31
        c00b30: 10.75.183.32
        c00b31: 10.75.183.33
        c00b32: 10.75.183.34
        # Frame 100.10
        # seagull and X3-2 computes
        c01b00: 10.75.183.57
        c01b01: 10.75.183.56
        c01b02: 10.75.183.55
        c01b03: 10.75.183.54
        c01b04: 10.75.183.53
        c01b05: 10.75.183.52
        c01b06: 10.75.183.51
        c01b07: 10.75.183.50
        # x5-2 computes
        c01b08: 10.75.183.48
        c01b09: 10.75.183.47
        c01b10: 10.75.183.46
        c01b11: 10.75.183.45
        c01b12: 10.75.183.44
        c01b13: 10.75.183.43
        c01b14: 10.75.183.42
        c01b15: 10.75.183.41
        c01b16: 10.75.183.40
        c01b17: 10.75.183.39
        c01b18: 10.75.183.38
        c01b19: 10.75.183.37
        # x4-2 controller(s)
        c01b20: 10.75.183.36
        c01b21: 10.75.183.35

    int_management_vlan:
      vlan_id: 22
      tagged_traffic_needed: false
      network: 172.31.0.0
      netmask: 255.255.0.0
      broadcast: 172.31.255.255
      host_min: 172.31.0.110
      host_max: 10.31.0.119
      gateway: 172.31.0.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.10
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem1
      utility_servers:
        bigcloud0100: 172.31.254.254
      blades:
        # Frame 100.09: X6-2 computes
        c00b00: 172.31.0.110
        c00b01: 172.31.0.111
        c00b02: 172.31.0.112
        c00b03: 172.31.0.113
        c00b04: 172.31.0.114
        c00b05: 172.31.0.115
        c00b06: 172.31.0.116
        c00b07: 172.31.0.117
        c00b08: 172.31.0.118
        c00b09: 172.31.0.119
        c00b10: 172.31.0.120
        c00b11: 172.31.0.121
        c00b12: 172.31.0.122
        c00b13: 172.31.0.123
        c00b14: 172.31.0.124
        c00b15: 172.31.0.125
        c00b16: 172.31.0.126
        c00b17: 172.31.0.127
        c00b18: 172.31.0.128
        c00b19: 172.31.0.129
        c00b20: 172.31.0.130
        c00b21: 172.31.0.131
        c00b22: 172.31.0.132
        c00b23: 172.31.0.133
        c00b24: 172.31.0.134
        c00b25: 172.31.0.135
        c00b26: 172.31.0.136
        c00b27: 172.31.0.137
        c00b28: 172.31.0.138
        c00b29: 172.31.0.139
        c00b30: 172.31.0.140
        c00b31: 172.31.0.141
        c00b32: 172.31.0.142
        # Frame 100.10
        # seagull and X3-2 computes
        c01b00: 172.31.1.110
        c01b01: 172.31.1.111
        c01b02: 172.31.1.112
        c01b03: 172.31.1.113
        c01b04: 172.31.1.114
        c01b05: 172.31.1.115
        c01b06: 172.31.1.116
        c01b07: 172.31.1.117
        # x5-2 computes
        c01b08: 172.31.1.118
        c01b09: 172.31.1.119
        c01b10: 172.31.1.120
        c01b11: 172.31.1.121
        c01b12: 172.31.1.122
        c01b13: 172.31.1.123
        c01b14: 172.31.1.124
        c01b15: 172.31.1.125
        c01b16: 172.31.1.126
        c01b17: 172.31.1.127
        c01b18: 172.31.1.128
        c01b19: 172.31.1.129
        # x4-2 controller(s)
        c01b20: 172.31.1.130
        c01b21: 172.31.1.131

    ilom_vlan:
      vlan_id: 23
      tagged_traffic_needed: false
      network: 10.75.128.0
      netmask: 255.255.252.0
      broadcast: 10.75.131.255
      host_min: 10.75.128.2
      host_max: 10.75.131.254
      gateway: 10.75.128.1
      ntp_server: 198.211.106.151
      zfs:
        zfs00:
          head00: 10.250.56.170
          head01: 10.250.56.171
      cmms:
        c00: 10.240.121.130
      nems:
        c00n00: 10.240.121.131
        c00n01: 10.240.121.132
      blades:
        # Frame 100.09: X6-2 computes
        c00b00: 10.75.129.140
        c00b01: 10.75.129.141
        c00b02: 10.75.129.142
        c00b03: 10.75.129.143
        c00b04: 10.75.129.144
        c00b05: 10.75.129.145
        c00b06: 10.75.129.146
        c00b07: 10.75.129.147
        c00b08: 10.75.129.148
        c00b09: 10.75.129.149
        c00b10: 10.75.129.150
        c00b11: 10.75.129.151
        c00b12: 10.75.129.152
        c00b13: 10.75.129.153
        c00b14: 10.75.129.154
        c00b15: 10.75.129.155
        c00b16: 10.75.129.156
        c00b17: 10.75.129.157
        c00b18: 10.75.129.158
        c00b19: 10.75.129.159
        c00b20: 10.75.129.160
        c00b21: 10.75.129.161
        c00b22: 10.75.129.162
        c00b23: 10.75.129.163
        c00b24: 10.75.129.164
        c00b25: 10.75.129.165
        c00b26: 10.75.129.166
        c00b27: 10.75.129.167
        c00b28: 10.75.129.168
        c00b29: 10.75.129.169
        c00b30: 10.75.129.170
        c00b31: 10.75.129.171
        c00b32: 10.75.129.172
        # Frame 100.10
        # seagull and X3-2 computes
        c01b00: 10.75.129.241
        c01b01: 10.75.129.242
        c01b02: 10.75.129.243
        c01b03: 10.75.129.244
        c01b04: 10.75.129.245
        c01b05: 10.75.129.246
        c01b06: 10.75.129.247
        c01b07: 10.75.129.248
        # x5-2 computes
        c01b08: 10.75.129.250
        c01b09: 10.75.129.251
        c01b10: 10.75.129.252
        c01b11: 10.75.129.253
        c01b12: 10.75.130.1
        c01b13: 10.75.130.2
        c01b14: 10.75.130.3
        c01b15: 10.75.130.4
        c01b16: 10.75.130.5
        c01b17: 10.75.130.6
        c01b18: 10.75.130.7
        c01b19: 10.75.130.8
        # x4-2 controller(s)
        c01b20: 10.75.130.9
        c01b21: 10.75.130.10
  dhcp_subnets:
    info:
      base: 172.31.0.0
      netmask: 255.255.0.0
      routers: 172.31.1.1
 
