---
lab_specifics:
  lab_id: big_cloud
  vlans:
    openstack_vxlan_tenant:
      vlan_id: 11
      tagged_traffic_needed: true
      network: 172.16.0.0
      netmask: 255.255.0.0

    openstack_provider_vlan:
      tagged_traffic_needed: true
      vlan_id: 10
      network: 10.75.183.0
      netmask: 255.255.255.128
      broadcast: 10.75.183.127 
      host_min: 10.75.183.65
      host_max: 10.75.183.126
      #openstack_reserved_first_address: 10.240.121.90
      #openstack_reserved_last_address: 10.240.121.100
      gateway: 10.75.183.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      utility_servers:
        big_cloud_dm0100: 10.75.183.3
    ext_management_vlan:
      tagged_traffic_needed: false
      vlan_id: 
      network: 10.75.183.0
      netmask: 255.255.255.128
      broadcast: 10.75.183.127
      host_min: 10.75.183.4
      host_max: 10.75.183.64
      gateway: 10.75.183.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      utility_servers:
        big_cloud_dm0100: 10.75.183.3
      zfs:
        zfs00:
          head00: 10.250.54.111
          head01: 10.250.54.112
      blades:
        c00b00: 10.75.183.4
        c00b01: 10.75.183.5
        c00b02: 10.75.183.6
        c00b03: 10.75.183.7
        c00b04: 10.75.183.8
        c00b05: 10.75.183.9
        c00b06: 10.75.183.10
        c00b07: 10.75.183.11
        c00b08: 10.75.183.12
        c00b09: 10.75.183.13
        c00b10: 10.75.183.14
        c00b11: 10.75.183.15
    int_management_vlan:
      vlan_id:
      tagged_traffic_needed: false
      network: 172.31.0.0
      netmask: 255.255.0.0
      broadcast: 172.31.255.255
      host_min: 172.31.0.110
      host_max: 10.31.0.119
      gateway: 172.31.0.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem1
      utility_servers:
        big_cloud_dm0100: 172.31.254.254
      blades:
        c00b00: 172.31.0.110
        c00b01: 172.31.0.111
        c00b02: 172.31.0.112
        c00b03: 172.31.0.113
        c00b04: 172.31.0.114
        c00b05: 172.31.0.115
        c00b06: 172.31.0.116
        c00b07: 172.31.0.117
        c00b08: 172.31.0.118
        c00b09: 172.31.0.119
        c00b10: 172.31.0.120
        c00b11: 172.31.0.121

    ilom_vlan:
      vlan_id: 
      tagged_traffic_needed: false
      network: 10.75.128.0
      netmask: 255.255.252.0
      broadcast: 10.75.131.255
      host_min: 10.75.128.2
      host_max: 10.75.131.254
      gateway: 10.75.128.1
      ntp_server: 198.211.106.151
      zfs:
        zfs00:
          head00: 10.250.56.170
          head01: 10.250.56.171
      cmms:
        c00: 10.240.121.130
      nems:
        c00n00: 10.240.121.131
        c00n01: 10.240.121.132
      blades:
        c00b00: 10.75.129.142
        c00b01: 10.75.129.143
        c00b02: 10.75.129.144
        c00b03: 10.75.129.145
        c00b04: 10.75.129.146
        c00b05: 10.75.129.147
        c00b06: 10.75.129.148
        c00b07: 10.75.129.149
        c00b08: 10.75.129.150
        c00b09: 10.75.129.151
        c00b10: 10.75.129.152
        c00b11: 10.75.129.153
     
     
     
  dhcp_subnets:
    info:
      base: 172.31.0.0
      netmask: 255.255.0.0
      routers: 172.31.1.1
 
