---
lab_specifics:
  lab_id: mvl
  vlans:
    openstack_provider_vlan:
      tagged_traffic_needed: true
      vlan_id: 586
      network: 10.240.121.0
      netmask: 255.255.255.192
      broadcast: 10.240.121.63
      host_min: 10.240.121.40
      host_max: 10.240.121.62
      #openstack_reserved_first_address: 10.240.121.90
      #openstack_reserved_last_address: 10.240.121.100
      gateway: 10.240.121.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      utility_servers:
        mvl0100: 10.240.121.66
    ext_management_vlan:
      tagged_traffic_needed: true
      vlan_id: 586
      network: 10.240.121.0
      netmask: 255.255.255.192
      broadcast: 10.240.121.63
      host_min: 10.240.121.1
      host_max: 10.240.121.19
      gateway: 10.240.121.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      utility_servers:
        mvl0100: 10.240.121.2
      zfs:
        zfs00:
          head00: 10.250.54.111
          head01: 10.250.54.112
      blades:
        c00b00: 10.240.121.10
        c00b01: 10.240.121.11
        c00b02: 10.240.121.12
        c00b03: 10.240.121.13
        c00b04: 10.240.121.14
        c00b05: 10.240.121.15
        c00b06: 10.240.121.16
        c00b07: 10.240.121.17
        c00b08: 10.240.121.18
        c00b09: 10.240.121.19
    int_management_vlan:
      vlan_id:
      tagged_traffic_needed: false
      network: 172.31.0.0
      netmask: 255.255.0.0
      broadcast: 172.31.255.255
      host_min: 172.31.0.110
      host_max: 10.31.0.119
      gateway: 172.31.0.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem1
      utility_servers:
        onap2100: 172.31.254.254
      blades:
        # chassis onap2
        c00b00: 172.31.0.110
        c00b01: 172.31.0.111
        c00b02: 172.31.0.112
        c00b03: 172.31.0.113
        c00b04: 172.31.0.114
        c00b05: 172.31.0.115
        c00b06: 172.31.0.116
        c00b07: 172.31.0.117
        c00b08: 172.31.0.118
        c00b09: 172.31.0.119

    ilom_vlan:
      vlan_id: 588
      tagged_traffic_needed: true
      network: 10.240.121.128
      netmask: 255.255.255.224
      broadcast: 10.240.121.129
      host_min: 10.240.121.129
      host_max: 10.240.121.158
      gateway: 10.240.121.129
      ntp_server: 198.211.106.151
      zfs:
        zfs00:
          head00: 10.250.56.170
          head01: 10.250.56.171
      cmms:
        c00: 10.240.121.130
      nems:
        c00n00: 10.240.121.131
        c00n01: 10.240.121.132
      blades:
        c00b00: 10.240.121.133
        c00b01: 10.240.121.134
        c00b02: 10.240.121.135
        c00b03: 10.240.121.136
        c00b04: 10.240.121.137
        c00b05: 10.240.121.138
        c00b06: 10.240.121.139
        c00b07: 10.240.121.140
        c00b08: 10.240.121.141
        c00b09: 10.240.121.142
     
  dhcp_subnets:
    info:
      base: 172.31.0.0
      netmask: 255.255.0.0
      routers: 172.31.1.1
 
