---
lab_specifics:
  lab_id: 101
  vlans:
    openstack_provider_vlan:
      vlan_id: 130
      tagged_traffic_needed: true
      network: 10.75.165.32
      netmask: 255.255.255.224
      broadcast: 10.75.165.63
      host_min: 10.75.165.44
      host_max: 10.75.165.62
      gateway: 10.75.165.33
      ntp_server: 10.250.32.10
      name_server: 10.209.76.197
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem1

    ext_management_vlan:
      vlan_id: 130
      tagged_traffic_needed: true
      network: 10.75.165.32
      netmask: 255.255.255.224
      broadcast: 10.75.165.63
      host_min: 10.75.165.34
      host_max: 10.75.165.43
      gateway: 10.75.165.33
      ntp_server: 10.250.32.10
      name_server: 10.209.76.197
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      blades:
        # chassis onap2
        c00b00: 10.75.165.35
        c00b01: 10.75.165.36
        c00b02: 10.75.165.37
        c00b03: 10.75.165.38
        c00b04: 10.75.165.39
        c00b05: 10.75.165.40
        c00b06: 10.75.165.41
        c00b07: 10.75.165.42
        c00b08: 10.75.165.43
      utility_servers:
        x5-200: 10.75.165.34

    int_management_vlan:
      vlan_id: 
      tagged_traffic_needed: false
      network: 172.31.0.0
      netmask: 255.255.0.0
      broadcast: 172.31.255.255
      host_min: 172.31.0.1
      host_max: 172.31.0.254
      gateway: 172.31.254.254
      ntp_server: 10.250.32.10
      name_server: 10.209.76.197
      name_server_search: "labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com."
      defined:
       - nem0
      utility_servers:
        x5-200: 172.31.254.254
      blades:
        c00b00: 172.31.0.110
        c00b01: 172.31.0.111
        c00b02: 172.31.0.112
        c00b03: 172.31.0.113
        c00b04: 172.31.0.114
        c00b05: 172.31.0.115
        c00b06: 172.31.0.116
        c00b07: 172.31.0.117
        c00b08: 172.31.0.118

    ilom_vlan:
      vlan_id:
      tagged_traffic_needed: false
      network: 10.75.129.0
      netmask: 255.255.255.0
      broadcast: 10.75.129.255
      cmms:
        c00: 172.31.2.253
      nems:
        c00n00: 172.31.2.251
        c00n01: 172.31.2.252
      blades:
        c00b00: 10.75.129.49
        c00b01: 10.75.129.50
        c00b02: 10.75.129.51
        c00b03: 10.75.129.52
        c00b04: 10.75.129.53
        c00b05: 10.75.129.54
        c00b06: 10.75.129.55
        c00b07: 10.75.129.56
        c00b08: 10.75.129.57
      utility_servers:
        x5-200: 10.75.129.48

  dhcp_subnets:
    info:
      base: 172.31.0.0
      netmask: 255.255.0.0
      routers: 172.31.254.254

