infrastructure:
  infra_id: x5-2
  vlans:
    openstack_vxlan_tenant:
      id: 16
      network: 172.16.0.0
      netmask: 255.255.0.0
      defined:
        - nem0
        - es2_72_tenant
    storage:
      id: 30
      network: 172.30.0.0
      netmask: 255.255.0.0
      defined:
        - nem1
        - es2_72_storage
    int_management_vlan:
      vlan_id: None
      tagged_traffic_needed: False
      network: 172.31.0.0
      netmask: 255.255.0.0
      broadcast: 172.31.255.255
      host_min: 172.31.2.1
      host_max: 172.31.2.254
      gateway: 172.31.0.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com.
      defined: ['nem0']
    ext_management_vlan:
      vlan_id: 1
      tagged_traffic_needed: False
      network: 10.250.65.0
      netmask: 255.255.255.0
      broadcast: 10.250.65.255
      host_min: 10.250.65.105
      host_max: 10.250.65.111
      gateway: 10.250.65.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com.
      defined: ['nem0']
    ilom_vlan:
      vlan_id: 3005
      tagged_traffic_needed: False
      network: 10.250.56.0
      netmask: 255.255.255.0
      broadcast: 10.250.65.255
    openstack_provider_vlan:
      vlan_id: None
      tagged_traffic_needed: False
      network: 10.250.65.0
      netmask: 255.255.255.0
      broadcast: 10.250.65.255
      host_min: 10.250.65.105
      host_max: 10.250.65.111
      gateway: 10.250.65.1
      ntp_server: 10.250.32.10
      name_server: 10.250.32.180
      name_server_search: labs.nc.tekelec.com. us.oracle.com. oraclecorp.com. oracle.com.
      defined: ['nem1']

  switches:

  zfs:

  dhcp_subnets:
    info:
      base: 172.31.0.0
      netmask: 255.255.0.0
      routers: 172.31.0.1
      next_server: 172.31.254.254

  utility_servers:
    x5-200:
      userv_id: x5-200
      userv_ilom_ip:  172.31.50.240
      userv_int_mgmt_ip: 172.31.254.254
      userv_int_mgmt_vlan_id: None
      userv_ext_mgmt_ip: 10.250.65.104
      userv_ext_mgmt_vlan_id: 1

  chassis:
    c00:
      cmm_id: c00
      cmm_ilom_ip: 172.31.2.253
      nems:
        c00n00:
          nem_id: c00n00
          nem_ilom_ip: 172.31.2.251
        c00n01:
          nem_id: c00n01
          nem_ilom_ip: 172.31.2.252
      blades:
        c00b00:
          blade_id: c00b00
          blade_hostname: c00b00
          blade_ilom_ip: 10.250.56.121
          blade_ilom_vlan_id: 3005
          blade_int_mgmt_ip: 172.31.2.110
          blade_ext_mgmt_ip: 10.250.65.102
          blade_ext_mgmt_vlan_id: 1
          blade_vlan16_ip: 172.16.0.110
          blade_vlan30_ip: 172.30.0.110
        c00b01:
          blade_id: c00b01
          blade_hostname: c00b01
          blade_ilom_ip: 10.250.56.123
          blade_ilom_vlan_id: 3005
          blade_int_mgmt_ip: 172.31.2.111
          blade_ext_mgmt_ip: 10.250.65.103
          blade_ext_mgmt_vlan_id: 1
          blade_vlan16_ip: 172.16.0.111
          blade_vlan30_ip: 172.30.0.111
        c00b02:
          blade_id: c00b02
          blade_hostname: c00b02
          blade_ilom_ip: 172.31.0.212
          blade_int_mgmt_ip: 172.31.0.112
          blade_vlan16_ip: 172.16.0.112
          blade_vlan30_ip: 172.30.0.112
        c00b03:
          blade_id: c00b03
          blade_hostname: c00b03
          blade_ilom_ip: 172.31.0.213
          blade_int_mgmt_ip: 172.31.0.113
          blade_vlan16_ip: 172.16.0.113
          blade_vlan30_ip: 172.30.0.113
        c00b04:
          blade_id: c00b04
          blade_hostname: c00b04
          blade_ilom_ip: 172.31.0.214
          blade_int_mgmt_ip: 172.31.0.114
          blade_vlan16_ip: 172.16.0.114
          blade_vlan30_ip: 172.30.0.114
        c00b05:
          blade_id: c00b05
          blade_hostname: c00b05
          blade_ilom_ip: 172.31.0.215
          blade_int_mgmt_ip: 172.31.0.115
          blade_vlan16_ip: 172.16.0.115
          blade_vlan30_ip: 172.30.0.115
        c00b06:
          blade_id: c00b06
          blade_hostname: c00b06
          blade_ilom_ip: 172.31.0.216
          blade_int_mgmt_ip: 172.31.0.116
          blade_vlan16_ip: 172.16.0.116
          blade_vlan30_ip: 172.30.0.116
        c00b07:
          blade_id: c00b07
          blade_hostname: c00b07
          blade_ilom_ip: 172.31.0.217
          blade_int_mgmt_ip: 172.31.0.117
          blade_vlan16_ip: 172.16.0.117
          blade_vlan30_ip: 172.30.0.117
        c00b08:
          blade_id: c00b08
          blade_hostname: c00b08
          blade_ilom_ip: 172.31.0.218
          blade_int_mgmt_ip: 172.31.0.118
          blade_vlan16_ip: 172.16.0.118
          blade_vlan30_ip: 172.30.0.118
        c00b09:
          blade_id: c00b09
          blade_hostname: c00b09
          blade_ilom_ip: 172.31.0.219
          blade_int_mgmt_ip: 172.31.0.119
          blade_vlan16_ip: 172.16.0.119
          blade_vlan30_ip: 172.30.0.119

