---
- name: load subnet variables
  include_vars: "{{ playbook_dir }}/roles/generate_vars/vars/main.yml"  
  run_once: true

- name: Installing openstack-nova-serialproxy
  yum: name=openstack-nova-serialproxy

### - name: Installing openstack-nova-serialproxy
###   yum: name=openstack-nova-serialproxy enablerepo=openstack-mitaka state=installed

- name: Starting and Enabling openstack-nova-serialproxy Service
  service: name=openstack-nova-serialproxy enabled=yes state=started

